# Generated by Django 4.0.10 on 2024-07-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job',
            new_name='jobs',
        ),
    ]
