# Generated by Django 4.0.10 on 2024-07-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=50)),
                ('developer_i', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('project_name', models.CharField(max_length=250)),
                ('process', models.CharField(max_length=250)),
                ('start_d', models.IntegerField()),
                ('end_d', models.IntegerField()),
                ('info', models.CharField(max_length=500)),
            ],
        ),
    ]
