# Generated by Django 4.0.10 on 2024-07-17 10:51

import deadline.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('developer_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Dasturchi',
                'verbose_name_plural': 'Dasturchilar',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jarayon',
                'verbose_name_plural': 'Jarayonlar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to=deadline.models.upload_to)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('info', models.CharField(max_length=500)),
                ('developer', models.ManyToManyField(to='deadline.developer')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deadline.domain')),
                ('process', models.ManyToManyField(to='deadline.process')),
            ],
            options={
                'verbose_name': 'Proyekt',
                'verbose_name_plural': 'Proyektlar',
            },
        ),
    ]
