# Generated by Django 4.0.10 on 2024-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
