# Generated by Django 4.0.10 on 2024-07-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='developer_i',
            new_name='developer_image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='developer',
            new_name='developer_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='end_d',
            new_name='end_day',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_d',
            new_name='start_day',
        ),
    ]
