# Generated by Django 4.0.10 on 2024-07-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0002_rename_developer_i_project_developer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ad_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deadline.additionalinfo'),
        ),
    ]
