# Generated by Django 4.0.10 on 2024-07-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0003_rename_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='task',
            new_name='status',
        ),
    ]
