# Generated by Django 4.0.10 on 2024-07-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0004_remove_project_developer_image_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_day',
            field=models.DateField(),
        ),
    ]
