# Generated by Django 4.0.10 on 2024-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0006_process_remove_project_ad_info_delete_additionalinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='process',
        ),
        migrations.AddField(
            model_name='project',
            name='process',
            field=models.ManyToManyField(to='deadline.process'),
        ),
    ]
