# Generated by Django 4.0.10 on 2024-07-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0009_domain_project_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deadline.project'),
        ),
    ]
