# Generated by Django 4.0.10 on 2024-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0010_remove_project_domain_domain_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='process',
        ),
        migrations.AddField(
            model_name='project',
            name='process',
            field=models.ManyToManyField(to='deadline.process'),
        ),
    ]
