# Generated by Django 4.0.10 on 2024-07-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0011_remove_project_process_project_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='process',
        ),
        migrations.AddField(
            model_name='project',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deadline.process'),
        ),
    ]
