# Generated by Django 4.0.10 on 2024-07-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0012_remove_project_process_project_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='process',
        ),
        migrations.AddField(
            model_name='project',
            name='process',
            field=models.ManyToManyField(to='deadline.process'),
        ),
    ]
