# Generated by Django 4.0.10 on 2024-07-16 06:28

import deadline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0013_remove_project_process_project_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to=deadline.models.upload_to),
        ),
    ]
