# Generated by Django 4.0.10 on 2024-07-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0014_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Jarayon', 'verbose_name_plural': 'Jarayonlar'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyekt', 'verbose_name_plural': 'Proyektalr'},
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='filed',
            new_name='field',
        ),
    ]
