# Generated by Django 4.0.10 on 2024-07-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0015_alter_domain_options_alter_process_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('developer_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyekt', 'verbose_name_plural': 'Proyektlar'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='developer_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='developer_name',
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deadline.developer'),
        ),
    ]
