# Generated by Django 4.0.10 on 2024-07-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0016_developer_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
