# Generated by Django 4.0.10 on 2024-07-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0017_project_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deadline.domain'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='developer',
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ManyToManyField(to='deadline.developer'),
        ),
    ]
