# Generated by Django 4.0.10 on 2024-07-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0018_remove_domain_project_project_domain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Dasturchi', 'verbose_name_plural': 'Dasturchilar'},
        ),
    ]
